build/card-08-A005-JP.o: build/trainers/alana-JP.mev

build/card-08-A001-EN.o: build/trainers/devin-EN.mev
build/card-08-A001-JP.o: build/trainers/devin-JP.mev
build/card-08-A002-EN.o: build/trainers/goro-EN.mev
build/card-08-A002-JP.o: build/trainers/goro-JP.mev
build/card-08-A003-EN.o: build/trainers/sonya-EN.mev
build/card-08-A003-JP.o: build/trainers/sonya-JP.mev
build/card-08-A004-EN.o: build/trainers/antonio-EN.mev
build/card-08-A004-JP.o: build/trainers/antonio-JP.mev
build/card-08-A005-EN.o: build/trainers/alana-EN.mev
build/card-08-A005-JP.o: build/trainers/alana-JP.mev
build/card-08-A006-EN.o: build/trainers/renee-EN.mev
build/card-08-A006-JP.o: build/trainers/renee-JP.mev
build/card-08-A007-EN.o: build/trainers/sophie-EN.mev
build/card-08-A007-JP.o: build/trainers/sophie-JP.mev
build/card-08-A008-EN.o: build/trainers/fay-EN.mev
build/card-08-A008-JP.o: build/trainers/fay-JP.mev
build/card-08-A009-EN.o: build/trainers/natasha-EN.mev
build/card-08-A009-JP.o: build/trainers/natasha-JP.mev
build/card-08-A010-EN.o: build/trainers/patrick-EN.mev
build/card-08-A010-JP.o: build/trainers/patrick-JP.mev
build/card-08-A011-EN.o: build/trainers/oscar-EN.mev
build/card-08-A011-JP.o: build/trainers/oscar-JP.mev
build/card-08-A012-EN.o: build/trainers/tyler-EN.mev
build/card-08-A012-JP.o: build/trainers/tyler-JP.mev
build/card-08-A013-EN.o: build/trainers/rudy-EN.mev
build/card-08-A013-JP.o: build/trainers/rudy-JP.mev
build/card-08-A014-EN.o: build/trainers/ellie-EN.mev
build/card-08-A014-JP.o: build/trainers/ellie-JP.mev
build/card-08-A015-EN.o: build/trainers/candice-EN.mev
build/card-08-A015-JP.o: build/trainers/candice-JP.mev
build/card-08-A016-EN.o: build/trainers/belford-EN.mev
build/card-08-A016-JP.o: build/trainers/belford-JP.mev
build/card-08-A017-EN.o: build/trainers/clayton-EN.mev
build/card-08-A017-JP.o: build/trainers/clayton-JP.mev
build/card-08-A018-EN.o: build/trainers/dustin-EN.mev
build/card-08-A018-JP.o: build/trainers/dustin-JP.mev
build/card-08-A019-EN.o: build/trainers/hugo-EN.mev
build/card-08-A019-JP.o: build/trainers/hugo-JP.mev
build/card-08-A020-EN.o: build/trainers/jeffrey-EN.mev
build/card-08-A020-JP.o: build/trainers/jeffrey-JP.mev
build/card-08-A021-EN.o: build/trainers/logan-EN.mev
build/card-08-A021-JP.o: build/trainers/logan-JP.mev
build/card-08-A022-EN.o: build/trainers/maggie-EN.mev
build/card-08-A022-JP.o: build/trainers/maggie-JP.mev
build/card-08-A023-EN.o: build/trainers/wilson-EN.mev
build/card-08-A023-JP.o: build/trainers/wilson-JP.mev
build/card-08-A024-EN.o: build/trainers/zuril-EN.mev
build/card-08-A024-JP.o: build/trainers/zuril-JP.mev
build/card-08-A025-EN.o: build/trainers/mandy-EN.mev
build/card-08-A025-JP.o: build/trainers/mandy-JP.mev
build/card-08-A026-EN.o: build/trainers/sofia-EN.mev
build/card-08-A026-JP.o: build/trainers/sofia-JP.mev
build/card-08-A027-EN.o: build/trainers/hillary-EN.mev
build/card-08-A027-JP.o: build/trainers/hillary-JP.mev
build/card-08-A028-EN.o: build/trainers/dominic-EN.mev
build/card-08-A028-JP.o: build/trainers/dominic-JP.mev
build/card-08-A029-EN.o: build/trainers/bryce-EN.mev
build/card-08-A029-JP.o: build/trainers/bryce-JP.mev
build/card-08-A030-EN.o: build/trainers/irvin-EN.mev
build/card-08-A030-JP.o: build/trainers/irvin-JP.mev
build/card-08-A031-EN.o: build/trainers/natalie-EN.mev
build/card-08-A031-JP.o: build/trainers/natalie-JP.mev
build/card-08-A032-EN.o: build/trainers/sandia-EN.mev
build/card-08-A032-JP.o: build/trainers/sandia-JP.mev
build/card-08-A033-EN.o: build/trainers/marcus-EN.mev
build/card-08-A033-JP.o: build/trainers/marcus-JP.mev
build/card-08-A034-EN.o: build/trainers/raquel-EN.mev
build/card-08-A034-JP.o: build/trainers/raquel-JP.mev
build/card-08-A035-EN.o: build/trainers/tsutomu-EN.mev
build/card-08-A035-JP.o: build/trainers/tsutomu-JP.mev
build/card-08-A036-EN.o: build/trainers/justine-EN.mev
build/card-08-A036-JP.o: build/trainers/justine-JP.mev
build/card-08-A037-EN.o: build/trainers/heather-EN.mev
build/card-08-A037-JP.o: build/trainers/heather-JP.mev
build/card-08-A038-EN.o: build/trainers/judith-EN.mev
build/card-08-A038-JP.o: build/trainers/judith-JP.mev
build/card-08-A039-EN.o: build/trainers/stuart-EN.mev
build/card-08-A039-JP.o: build/trainers/stuart-JP.mev
build/card-08-A040-EN.o: build/trainers/irazu-EN.mev
build/card-08-A040-JP.o: build/trainers/irazu-JP.mev
build/card-08-A041-EN.o: build/trainers/sandy-EN.mev
build/card-08-A041-JP.o: build/trainers/sandy-JP.mev
build/card-08-A042-EN.o: build/trainers/annie-EN.mev
build/card-08-A042-JP.o: build/trainers/annie-JP.mev
build/card-08-A043-EN.o: build/trainers/celina-EN.mev
build/card-08-A043-JP.o: build/trainers/celina-JP.mev
build/card-08-A044-EN.o: build/trainers/april-EN.mev
build/card-08-A044-JP.o: build/trainers/april-JP.mev
build/card-08-A045-EN.o: build/trainers/hayden-EN.mev
build/card-08-A045-JP.o: build/trainers/hayden-JP.mev
build/card-08-A046-EN.o: build/trainers/griffin-EN.mev
build/card-08-A046-JP.o: build/trainers/griffin-JP.mev
build/card-08-A047-EN.o: build/trainers/kendall-EN.mev
build/card-08-A047-JP.o: build/trainers/kendall-JP.mev
build/card-08-A048-EN.o: build/trainers/fuego-EN.mev
build/card-08-A048-JP.o: build/trainers/fuego-JP.mev
build/card-08-B001-EN.o: build/trainers/mami-EN.mev
build/card-08-B001-JP.o: build/trainers/mami-JP.mev
build/card-08-B002-EN.o: build/trainers/toshitsugu-EN.mev
build/card-08-B002-JP.o: build/trainers/toshitsugu-JP.mev
build/card-08-B003-EN.o: build/trainers/koto-EN.mev
build/card-08-B003-JP.o: build/trainers/koto-JP.mev
build/card-08-B004-EN.o: build/trainers/masaru-EN.mev
build/card-08-B004-JP.o: build/trainers/masaru-JP.mev
build/card-08-B005-EN.o: build/trainers/harue-EN.mev
build/card-08-B005-JP.o: build/trainers/harue-JP.mev
build/card-08-B006-EN.o: build/trainers/yu-EN.mev
build/card-08-B006-JP.o: build/trainers/yu-JP.mev
build/card-08-B007-EN.o: build/trainers/matsuo-EN.mev
build/card-08-B007-JP.o: build/trainers/matsuo-JP.mev
build/card-08-B008-EN.o: build/trainers/kuen-EN.mev
build/card-08-B008-JP.o: build/trainers/kuen-JP.mev
build/card-08-B009-EN.o: build/trainers/shizu-EN.mev
build/card-08-B009-JP.o: build/trainers/shizu-JP.mev
build/card-08-B010-EN.o: build/trainers/junpei-EN.mev
build/card-08-B010-JP.o: build/trainers/junpei-JP.mev
build/card-08-B011-EN.o: build/trainers/jo-EN.mev
build/card-08-B011-JP.o: build/trainers/jo-JP.mev
build/card-08-B012-EN.o: build/trainers/fiennes-EN.mev
build/card-08-B012-JP.o: build/trainers/fiennes-JP.mev
build/card-08-B013-EN.o: build/trainers/danpei-EN.mev
build/card-08-B013-JP.o: build/trainers/danpei-JP.mev
build/card-08-B014-EN.o: build/trainers/yuka-EN.mev
build/card-08-B014-JP.o: build/trainers/yuka-JP.mev
build/card-08-B015-EN.o: build/trainers/yoko-EN.mev
build/card-08-B015-JP.o: build/trainers/yoko-JP.mev
build/card-08-B016-EN.o: build/trainers/fukune-EN.mev
build/card-08-B016-JP.o: build/trainers/fukune-JP.mev
build/card-08-B017-EN.o: build/trainers/kiyoshi-EN.mev
build/card-08-B017-JP.o: build/trainers/kiyoshi-JP.mev
build/card-08-B018-EN.o: build/trainers/toshinao-EN.mev
build/card-08-B018-JP.o: build/trainers/toshinao-JP.mev
build/card-08-B019-EN.o: build/trainers/otoya-EN.mev
build/card-08-B019-JP.o: build/trainers/otoya-JP.mev
build/card-08-B020-EN.o: build/trainers/natsuko-EN.mev
build/card-08-B020-JP.o: build/trainers/natsuko-JP.mev
build/card-08-B021-EN.o: build/trainers/sadayo-EN.mev
build/card-08-B021-JP.o: build/trainers/sadayo-JP.mev
build/card-08-B022-EN.o: build/trainers/junji-EN.mev
build/card-08-B022-JP.o: build/trainers/junji-JP.mev
build/card-08-B023-EN.o: build/trainers/shinji-EN.mev
build/card-08-B023-JP.o: build/trainers/shinji-JP.mev
build/card-08-B024-EN.o: build/trainers/fugen-EN.mev
build/card-08-B024-JP.o: build/trainers/fugen-JP.mev
build/card-08-B025-EN.o: build/trainers/rina-EN.mev
build/card-08-B025-JP.o: build/trainers/rina-JP.mev
build/card-08-B026-EN.o: build/trainers/ruizo-EN.mev
build/card-08-B026-JP.o: build/trainers/ruizo-JP.mev
build/card-08-B027-EN.o: build/trainers/nozomu-EN.mev
build/card-08-B027-JP.o: build/trainers/nozomu-JP.mev
build/card-08-B028-EN.o: build/trainers/kyohei-EN.mev
build/card-08-B028-JP.o: build/trainers/kyohei-JP.mev
build/card-08-B029-EN.o: build/trainers/yukio-EN.mev
build/card-08-B029-JP.o: build/trainers/yukio-JP.mev
build/card-08-B030-EN.o: build/trainers/makio-EN.mev
build/card-08-B030-JP.o: build/trainers/makio-JP.mev
build/card-08-B031-EN.o: build/trainers/noriko-EN.mev
build/card-08-B031-JP.o: build/trainers/noriko-JP.mev
build/card-08-B032-EN.o: build/trainers/hoyoshi-EN.mev
build/card-08-B032-JP.o: build/trainers/hoyoshi-JP.mev
build/card-08-B033-EN.o: build/trainers/tomoyasu-EN.mev
build/card-08-B033-JP.o: build/trainers/tomoyasu-JP.mev
build/card-08-B034-EN.o: build/trainers/anthony-EN.mev
build/card-08-B034-JP.o: build/trainers/anthony-JP.mev
build/card-08-B035-EN.o: build/trainers/ryo-EN.mev
build/card-08-B035-JP.o: build/trainers/ryo-JP.mev
build/card-08-B036-EN.o: build/trainers/daikichi-EN.mev
build/card-08-B036-JP.o: build/trainers/daikichi-JP.mev
build/card-08-B037-EN.o: build/trainers/shigenobu-EN.mev
build/card-08-B037-JP.o: build/trainers/shigenobu-JP.mev
build/card-08-B038-EN.o: build/trainers/reina-EN.mev
build/card-08-B038-JP.o: build/trainers/reina-JP.mev
build/card-08-B039-EN.o: build/trainers/momoko-EN.mev
build/card-08-B039-JP.o: build/trainers/momoko-JP.mev
build/card-08-B040-EN.o: build/trainers/ihara-EN.mev
build/card-08-B040-JP.o: build/trainers/ihara-JP.mev
build/card-08-B041-EN.o: build/trainers/satoe-EN.mev
build/card-08-B041-JP.o: build/trainers/satoe-JP.mev
build/card-08-B042-EN.o: build/trainers/suekichi-EN.mev
build/card-08-B042-JP.o: build/trainers/suekichi-JP.mev
build/card-08-B043-EN.o: build/trainers/miyoko-EN.mev
build/card-08-B043-JP.o: build/trainers/miyoko-JP.mev
build/card-08-B044-EN.o: build/trainers/moet-EN.mev
build/card-08-B044-JP.o: build/trainers/moet-JP.mev
build/card-08-B045-EN.o: build/trainers/chisa-EN.mev
build/card-08-B045-JP.o: build/trainers/chisa-JP.mev
build/card-08-B046-EN.o: build/trainers/sueno-EN.mev
build/card-08-B046-JP.o: build/trainers/sueno-JP.mev
build/card-08-B047-EN.o: build/trainers/shigeko-EN.mev
build/card-08-B047-JP.o: build/trainers/shigeko-JP.mev
build/card-08-B048-EN.o: build/trainers/umami-EN.mev
build/card-08-B048-JP.o: build/trainers/umami-JP.mev
build/card-08-N001-EN.o: build/trainers/teruko-EN.mev
build/card-08-N001-JP.o: build/trainers/teruko-JP.mev
build/card-08-N002-EN.o: build/trainers/kimiko-EN.mev
build/card-08-N002-JP.o: build/trainers/kimiko-JP.mev
build/card-08-N003-EN.o: build/trainers/norton-EN.mev
build/card-08-N003-JP.o: build/trainers/norton-JP.mev
build/card-08-N004-EN.o: build/trainers/simon-EN.mev
build/card-08-N004-JP.o: build/trainers/simon-JP.mev
build/card-08-N005-EN.o: build/trainers/hozumi-EN.mev
build/card-08-N005-JP.o: build/trainers/hozumi-JP.mev
build/card-08-N006-EN.o: build/trainers/ritsue-EN.mev
build/card-08-N006-JP.o: build/trainers/ritsue-JP.mev
build/card-08-N007-EN.o: build/trainers/yuuma-EN.mev
build/card-08-N007-JP.o: build/trainers/yuuma-JP.mev
build/card-08-N008-EN.o: build/trainers/taisen-EN.mev
build/card-08-N008-JP.o: build/trainers/taisen-JP.mev
build/card-08-P001-EN.o: build/trainers/craig-EN.mev
build/card-08-P001-JP.o: build/trainers/craig-JP.mev
build/card-08-P002-EN.o: build/trainers/yasuo-EN.mev
build/card-08-P002-JP.o: build/trainers/yasuo-JP.mev
build/card-08-P003-EN.o: build/trainers/darlene-EN.mev
build/card-08-P003-JP.o: build/trainers/darlene-JP.mev
build/card-08-P004-EN.o: build/trainers/mattego-EN.mev
build/card-08-P004-JP.o: build/trainers/mattego-JP.mev
build/card-08-P005-EN.o: build/trainers/hidehiko-EN.mev
build/card-08-P005-JP.o: build/trainers/hidehiko-JP.mev
build/card-08-P006-EN.o: build/trainers/yufu-EN.mev
build/card-08-P006-JP.o: build/trainers/yufu-JP.mev
build/card-08-P007-EN.o: build/trainers/sagami-EN.mev
build/card-08-P007-JP.o: build/trainers/sagami-JP.mev
build/card-08-P008-EN.o: build/trainers/mattegoDEMO-EN.mev
build/card-08-P008-JP.o: build/trainers/mattegoDEMO-JP.mev
build/card-129-B001-EN.o: build/trainers/nils-EN.mev
build/card-129-B001-JP.o: build/trainers/nils-JP.mev
build/card-129-B002-EN.o: build/trainers/astrid-EN.mev
build/card-129-B002-JP.o: build/trainers/astrid-JP.mev

# Custom series trainers
build/card-99-A001-EN.o: build/trainers/fex-EN.mev
