DEF END_OF_CHUNKS    EQU $02
DEF LOADING_MESSAGE  EQU $03
DEF SET_LOAD_STATUS  EQU $04
DEF PRELOAD_SCRIPT   EQU $05
DEF IN_GAME_SCRIPT   EQU $06
DEF CUSTOM_BERRY     EQU $07
DEF AWARD_RIBBON     EQU $08
DEF NATIONAL_POKEDEX EQU $09
DEF ADD_RARE_WORD    EQU $0A
DEF MIX_RECORDS_ITEM EQU $0B
DEF GIVE_POKEMON     EQU $0C
DEF BATTLE_TRAINER   EQU $0D
DEF CLOCK_ADJUSTMENT EQU $0E
DEF CHECKSUM_BYTES   EQU $0F ; don’t use this
DEF CHECKSUM_CRC     EQU $10 ; use this instead
DEF DOME_TRAINER     EQU $11 ; Battle Dome trainer
