name: Match cards 
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  VerifyAll:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Verify gift 
        run: |
          cd src && make generate && make verify
